

name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main
      - gh-pages
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: list
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SOGIRLE }}'
          channelId: live
          projectId: sogirle
